Fri Dec  3 22:43:43 2021

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/nextcord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 199, in on_connect
    for guild_id in bot.cache.get_guilds(bot): # Obtain all guilds the cache stores data (will need to be upgraded.)
TypeError: 'coroutine' object is not iterable


Fri Dec  3 22:45:21 2021

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/nextcord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 199, in on_connect
    for guild_id in bot.cache.get_guilds(bot): # Obtain all guilds the cache stores data (will need to be upgraded.)
TypeError: 'coroutine' object is not iterable


Fri Dec  3 22:46:36 2021

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/nextcord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 199, in on_connect
    for guild_id in bot.cache.get_guilds(bot): # Obtain all guilds the cache stores data (will need to be upgraded.)
TypeError: 'coroutine' object is not iterable


Fri Dec  3 23:47:43 2021

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/nextcord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 236, in on_slash_command_error
    return await inter.reply(**base_on_error(inter, error))
TypeError: reply() argument after ** must be a mapping, not coroutine


