Sat Dec 11 01:15:56 2021

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/slash_client.py", line 1275, in _on_slash_command
    await app_command.invoke(inter)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/slash_core.py", line 362, in invoke
    raise err
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/slash_core.py", line 358, in invoke
    await self._maybe_cog_call(self._cog, interaction, interaction.data)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/slash_core.py", line 112, in _maybe_cog_call
    return await self(cog, inter, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/core.py", line 72, in __call__
    return await self.func(*args, **kwargs)
  File "/home/runner/TheDiscordMathProblemBot/cogs/misc_commands_cog.py", line 117, in list_trusted_users
    user = await self.bot.fetch_user(user_id=user_id)
TypeError: fetch_user() got some positional-only arguments passed as keyword arguments: 'user_id'


Sat Dec 11 17:25:19 2021

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/nextcord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 271, in on_guild_remove
    await bot.cache.remove_all_by_guild_id(guild.id)  # Remove all guild-related stuff
AttributeError: 'MathProblemCache' object has no attribute 'remove_all_by_guild_id'


Sat Dec 11 18:12:12 2021

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/slash_client.py", line 1275, in _on_slash_command
    await app_command.invoke(inter)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/slash_core.py", line 362, in invoke
    raise err
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/slash_core.py", line 358, in invoke
    await self._maybe_cog_call(self._cog, interaction, interaction.data)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/slash_core.py", line 112, in _maybe_cog_call
    return await self(cog, inter, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/core.py", line 72, in __call__
    return await self.func(*args, **kwargs)
  File "/home/runner/TheDiscordMathProblemBot/cogs/problems_cog.py", line 284, in list_all_problems
    for problem in await self.cache.get_guild_problems(guild_id):
  File "/home/runner/TheDiscordMathProblemBot/helpful_modules/problems_module/cache.py", line 442, in get_guild_problems
    return self.guild_problems[Guild.id]
AttributeError: 'int' object has no attribute 'id'


